name: Release Windows
on:
  # 手动触发
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: windows-2019
    steps:
      # 使用本项目
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: PyInstaller
        run: |
          python script/packagescript.py


      # Upload generated apk to the artifacts.
      - uses: actions/upload-artifact@v3.1.3
        with:
          # Artifact name
          name: windows-release.zip
          # 导出文件夹
          path: script/dist/
          # The desired behavior if no files are found using the provided path.

